<?php

namespace App\Services;

use App\Models\Document;
use App\Models\KnowledgeMemory;
use App\Models\User;
use App\Repositories\DocumentRepository;
use App\Services\Document\DocumentProcessorService;
use App\Services\Workspace\WorkspaceResolver;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class DocumentService
{
    public function __construct(
        protected DocumentRepository $documentRepository,
        protected DocumentProcessorService $documentProcessorService,
        protected WorkspaceResolver $workspaceResolver,
    ) {}

    public function getDocuments(User $user)
    {
        $workspace = $this->workspaceResolver->resolve($user);

        return $this->documentRepository
            ->getByWorkspace($workspace->id);
    }

    public function getDocumentForPreview(User $user, Document $document): Document
    {
        $workspace = $this->workspaceResolver->resolve($user);
        abort_if($document->workspace_id !== $workspace->id, 403, 'Unauthorized access to document.');

        $document->load('content');
        return $document;
    }

    public function archive(User $user, Document $document): Document
    {
        $workspace = $this->workspaceResolver->resolve($user);
        abort_if($document->workspace_id !== $workspace->id, 403, 'Unauthorized access to document.');

        return $this->documentRepository->update($document, ['status' => 'archived']);
    }

    public function restore(User $user, Document $document): Document
    {
        $workspace = $this->workspaceResolver->resolve($user);
        abort_if($document->workspace_id !== $workspace->id, 403, 'Unauthorized access to document.');

        return $this->documentRepository->update($document, ['status' => 'ready']);
    }

    public function delete(User $user, Document $document): void
    {
        $workspace = $this->workspaceResolver->resolve($user);
        abort_if($document->workspace_id !== $workspace->id, 403, 'Unauthorized access to document.');

        DB::transaction(function () use ($document) {
            // 1. Wipe specific Knowledge Memory generated by this document
            KnowledgeMemory::where('workspace_id', $document->workspace_id)
                ->where('source_type', 'document')
                ->where('source_id', $document->id)
                ->delete();

            // 2. Wipe Extracted Content
            if ($document->content) {
                $document->content()->delete();
            }

            // 3. Delete Physical File
            if (Storage::disk('local')->exists($document->file_path)) {
                Storage::disk('local')->delete($document->file_path);
            }

            // 4. Delete Record
            $this->documentRepository->delete($document);
        });
    }

    public function upload(
        User $user,
        string $title,
        UploadedFile $file
    ): Document {
        return DB::transaction(function () use ($user, $title, $file) {

            $workspace = $this->workspaceResolver->resolve($user);

            $fileName = Str::uuid() . '.' . $file->getClientOriginalExtension();

            $path = $file->storeAs(
                "documents/{$workspace->id}",
                $fileName,
                'local'
            );

            $document = $this->documentRepository->create([
                'workspace_id' => $workspace->id,
                'uploaded_by'  => $user->id,
                'title'        => $title,
                'file_name'    => $fileName,
                'file_path'    => $path,
                'mime_type'    => $file->getMimeType(),
                'file_size'    => $file->getSize(),
                'status'       => 'pending',
            ]);

            $this->documentProcessorService->process($document);

            return $document;
        });
    }

    public function buildContext(
        User $user,
        string $question
    ): array {
        $workspace = $this->workspaceResolver->resolve($user);

        return $this->documentRepository->searchRelevantDocuments(
            $workspace->id,
            $question
        );
    }
}